name: Kernel CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v2

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1 ccache
        sudo git clone --depth 1 --branch android-5.1.1_r28 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 /opt/toolchains/aarch64-linux-android-4.9/
    - name: Building Kernel
      run: |
        export KBUILD_BUILD_USER=notnoelchannel
        export KBUILD_BUILD_HOST=unlegacy-devices
        make -j22 msm8916_sec_defconfig VARIANT_DEFCONFIG=msm8916_sec_j3lte_spr_defconfig SELINUX_DEFCONFIG=selinux_defconfig
        make -j128
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp arch/arm/boot/Image /home/runner/work/output/zImage
        find . -name "*.ko" -exec cp {} /home/runner/work/output/ \;
    - name: Uploading Output
      uses: actions/upload-artifact@v2
      with:
        name: zImage
        path: /home/runner/work/output/zImage
        
    - name: Uploading Modules
      uses: actions/upload-artifact@v2
      with:
        name: modules
        path: /home/runner/work/output/*.ko
